-- SQL Logging Session
-- Session ID: 6117d6d5-6cae-4042-91c3-4be160eec6ee
-- Started: 2026-06-23T21:14:52.199Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
DECLARE @ID_45bb317a UNIQUEIDENTIFIER,
@Name_45bb317a NVARCHAR(100),
@Description_45bb317a NVARCHAR(MAX),
@IconClass_45bb317a NVARCHAR(100),
@DefaultPriority_45bb317a NVARCHAR(20),
@OnAssignActionID_45bb317a UNIQUEIDENTIFIER,
@OnCompleteActionID_45bb317a UNIQUEIDENTIFIER,
@OnOverdueActionID_45bb317a UNIQUEIDENTIFIER,
@OnPercentChangeActionID_45bb317a UNIQUEIDENTIFIER,
@IsActive_45bb317a BIT,
@OnRejectActionID_45bb317a UNIQUEIDENTIFIER,
@OnCancelActionID_45bb317a UNIQUEIDENTIFIER
SET
  @ID_45bb317a = '5961EDE5-B996-4083-BE48-64634B4D8D1C'
SET
  @Name_45bb317a = N'Approval Request'
SET
  @Description_45bb317a = N'An approval/decision workflow request routed to one or more approvers. Consumers wire OnReject/OnCancel/OnComplete actions to feed the decision back to the source record.'
SET
  @IconClass_45bb317a = N'fa-solid fa-stamp'
SET
  @DefaultPriority_45bb317a = N'High'
SET
  @IsActive_45bb317a = 1
EXEC [__mj_BizAppsTasks].spCreateTaskType @ID = @ID_45bb317a,
  @Name = @Name_45bb317a,
  @Description = @Description_45bb317a,
  @IconClass = @IconClass_45bb317a,
  @DefaultPriority = @DefaultPriority_45bb317a,
  @OnAssignActionID = @OnAssignActionID_45bb317a,
  @OnAssignActionID_Clear = 1,
  @OnCompleteActionID = @OnCompleteActionID_45bb317a,
  @OnCompleteActionID_Clear = 1,
  @OnOverdueActionID = @OnOverdueActionID_45bb317a,
  @OnOverdueActionID_Clear = 1,
  @OnPercentChangeActionID = @OnPercentChangeActionID_45bb317a,
  @OnPercentChangeActionID_Clear = 1,
  @IsActive = @IsActive_45bb317a,
  @OnRejectActionID = @OnRejectActionID_45bb317a,
  @OnRejectActionID_Clear = 1,
  @OnCancelActionID = @OnCancelActionID_45bb317a,
  @OnCancelActionID_Clear = 1;

GO

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (core SP call only)
DECLARE @ID_f7145d84 UNIQUEIDENTIFIER,
@Name_f7145d84 NVARCHAR(100),
@Code_f7145d84 NVARCHAR(50),
@Description_f7145d84 NVARCHAR(MAX),
@Sequence_f7145d84 INT,
@IsTerminal_f7145d84 BIT,
@IsActive_f7145d84 BIT
SET
  @ID_f7145d84 = '17597703-5724-4FC8-8A13-28CF5BA96E05'
SET
  @Name_f7145d84 = N'Approved'
SET
  @Code_f7145d84 = N'Approved'
SET
  @Description_f7145d84 = N'The request was approved without conditions.'
SET
  @Sequence_f7145d84 = 10
SET
  @IsTerminal_f7145d84 = 1
SET
  @IsActive_f7145d84 = 1
EXEC [__mj_BizAppsTasks].spCreateTaskDecisionOutcome @ID = @ID_f7145d84,
  @Name = @Name_f7145d84,
  @Code = @Code_f7145d84,
  @Description = @Description_f7145d84,
  @Sequence = @Sequence_f7145d84,
  @IsTerminal = @IsTerminal_f7145d84,
  @IsActive = @IsActive_f7145d84;

GO

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (core SP call only)
DECLARE @ID_ffb26e89 UNIQUEIDENTIFIER,
@Name_ffb26e89 NVARCHAR(100),
@Code_ffb26e89 NVARCHAR(50),
@Description_ffb26e89 NVARCHAR(MAX),
@Sequence_ffb26e89 INT,
@IsTerminal_ffb26e89 BIT,
@IsActive_ffb26e89 BIT
SET
  @ID_ffb26e89 = '94C600A5-2CAB-4B52-A9D2-995768EAABD5'
SET
  @Name_ffb26e89 = N'Rejected'
SET
  @Code_ffb26e89 = N'Rejected'
SET
  @Description_ffb26e89 = N'The request was rejected.'
SET
  @Sequence_ffb26e89 = 20
SET
  @IsTerminal_ffb26e89 = 1
SET
  @IsActive_ffb26e89 = 1
EXEC [__mj_BizAppsTasks].spCreateTaskDecisionOutcome @ID = @ID_ffb26e89,
  @Name = @Name_ffb26e89,
  @Code = @Code_ffb26e89,
  @Description = @Description_ffb26e89,
  @Sequence = @Sequence_ffb26e89,
  @IsTerminal = @IsTerminal_ffb26e89,
  @IsActive = @IsActive_ffb26e89;

GO

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (core SP call only)
DECLARE @ID_13e57da9 UNIQUEIDENTIFIER,
@Name_13e57da9 NVARCHAR(100),
@Code_13e57da9 NVARCHAR(50),
@Description_13e57da9 NVARCHAR(MAX),
@Sequence_13e57da9 INT,
@IsTerminal_13e57da9 BIT,
@IsActive_13e57da9 BIT
SET
  @ID_13e57da9 = '06C79086-AC2D-4E54-ADDB-CCAFC46D0DB7'
SET
  @Name_13e57da9 = N'Approved With Conditions'
SET
  @Code_13e57da9 = N'ApprovedWithConditions'
SET
  @Description_13e57da9 = N'The request was approved subject to the conditions in the decision notes.'
SET
  @Sequence_13e57da9 = 30
SET
  @IsTerminal_13e57da9 = 1
SET
  @IsActive_13e57da9 = 1
EXEC [__mj_BizAppsTasks].spCreateTaskDecisionOutcome @ID = @ID_13e57da9,
  @Name = @Name_13e57da9,
  @Code = @Code_13e57da9,
  @Description = @Description_13e57da9,
  @Sequence = @Sequence_13e57da9,
  @IsTerminal = @IsTerminal_13e57da9,
  @IsActive = @IsActive_13e57da9;

GO


-- End of SQL Logging Session
-- Session ID: 6117d6d5-6cae-4042-91c3-4be160eec6ee
-- Completed: 2026-06-23T21:14:52.582Z
-- Duration: 383ms
-- Total Statements: 4
