-- SQL Logging Session
-- Session ID: d22fb82f-8795-4d89-b6b4-09cee42fcb33
-- Started: 2026-06-10T21:14:43.435Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
DECLARE @ID_7c1991f8 UNIQUEIDENTIFIER,
@Name_7c1991f8 NVARCHAR(100),
@Description_7c1991f8 NVARCHAR(MAX),
@IconClass_7c1991f8 NVARCHAR(100),
@DefaultPriority_7c1991f8 NVARCHAR(20),
@OnAssignActionID_7c1991f8 UNIQUEIDENTIFIER,
@OnCompleteActionID_7c1991f8 UNIQUEIDENTIFIER,
@OnOverdueActionID_7c1991f8 UNIQUEIDENTIFIER,
@OnPercentChangeActionID_7c1991f8 UNIQUEIDENTIFIER,
@IsActive_7c1991f8 BIT
SET
  @ID_7c1991f8 = 'F7C1E8DE-8DAC-4BF8-943E-3D5A1210BE82'
SET
  @Name_7c1991f8 = N'General'
SET
  @Description_7c1991f8 = N'General-purpose task'
SET
  @IconClass_7c1991f8 = N'fa-solid fa-circle-check'
SET
  @DefaultPriority_7c1991f8 = N'Medium'
SET
  @IsActive_7c1991f8 = 1
EXEC [__mj_BizAppsTasks].spCreateTaskType @ID = @ID_7c1991f8,
  @Name = @Name_7c1991f8,
  @Description = @Description_7c1991f8,
  @IconClass = @IconClass_7c1991f8,
  @DefaultPriority = @DefaultPriority_7c1991f8,
  @OnAssignActionID = @OnAssignActionID_7c1991f8,
  @OnAssignActionID_Clear = 1,
  @OnCompleteActionID = @OnCompleteActionID_7c1991f8,
  @OnCompleteActionID_Clear = 1,
  @OnOverdueActionID = @OnOverdueActionID_7c1991f8,
  @OnOverdueActionID_Clear = 1,
  @OnPercentChangeActionID = @OnPercentChangeActionID_7c1991f8,
  @OnPercentChangeActionID_Clear = 1,
  @IsActive = @IsActive_7c1991f8;

GO

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
DECLARE @ID_9beba79b UNIQUEIDENTIFIER,
@Name_9beba79b NVARCHAR(100),
@Description_9beba79b NVARCHAR(MAX),
@IconClass_9beba79b NVARCHAR(100),
@DefaultPriority_9beba79b NVARCHAR(20),
@OnAssignActionID_9beba79b UNIQUEIDENTIFIER,
@OnCompleteActionID_9beba79b UNIQUEIDENTIFIER,
@OnOverdueActionID_9beba79b UNIQUEIDENTIFIER,
@OnPercentChangeActionID_9beba79b UNIQUEIDENTIFIER,
@IsActive_9beba79b BIT
SET
  @ID_9beba79b = 'EA525DE3-B4A9-471C-AD13-1881E2055121'
SET
  @Name_9beba79b = N'Action Item'
SET
  @Description_9beba79b = N'Action item from a meeting or discussion'
SET
  @IconClass_9beba79b = N'fa-solid fa-bolt'
SET
  @DefaultPriority_9beba79b = N'Medium'
SET
  @IsActive_9beba79b = 1
EXEC [__mj_BizAppsTasks].spCreateTaskType @ID = @ID_9beba79b,
  @Name = @Name_9beba79b,
  @Description = @Description_9beba79b,
  @IconClass = @IconClass_9beba79b,
  @DefaultPriority = @DefaultPriority_9beba79b,
  @OnAssignActionID = @OnAssignActionID_9beba79b,
  @OnAssignActionID_Clear = 1,
  @OnCompleteActionID = @OnCompleteActionID_9beba79b,
  @OnCompleteActionID_Clear = 1,
  @OnOverdueActionID = @OnOverdueActionID_9beba79b,
  @OnOverdueActionID_Clear = 1,
  @OnPercentChangeActionID = @OnPercentChangeActionID_9beba79b,
  @OnPercentChangeActionID_Clear = 1,
  @IsActive = @IsActive_9beba79b;

GO

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
DECLARE @ID_28979e8d UNIQUEIDENTIFIER,
@Name_28979e8d NVARCHAR(100),
@Description_28979e8d NVARCHAR(MAX),
@IconClass_28979e8d NVARCHAR(100),
@DefaultPriority_28979e8d NVARCHAR(20),
@OnAssignActionID_28979e8d UNIQUEIDENTIFIER,
@OnCompleteActionID_28979e8d UNIQUEIDENTIFIER,
@OnOverdueActionID_28979e8d UNIQUEIDENTIFIER,
@OnPercentChangeActionID_28979e8d UNIQUEIDENTIFIER,
@IsActive_28979e8d BIT
SET
  @ID_28979e8d = 'EE1A6B5A-A5AD-4A62-89DB-D16FFD2A415C'
SET
  @Name_28979e8d = N'Follow-up'
SET
  @Description_28979e8d = N'Follow-up on a previous discussion or decision'
SET
  @IconClass_28979e8d = N'fa-solid fa-arrow-rotate-right'
SET
  @DefaultPriority_28979e8d = N'Medium'
SET
  @IsActive_28979e8d = 1
EXEC [__mj_BizAppsTasks].spCreateTaskType @ID = @ID_28979e8d,
  @Name = @Name_28979e8d,
  @Description = @Description_28979e8d,
  @IconClass = @IconClass_28979e8d,
  @DefaultPriority = @DefaultPriority_28979e8d,
  @OnAssignActionID = @OnAssignActionID_28979e8d,
  @OnAssignActionID_Clear = 1,
  @OnCompleteActionID = @OnCompleteActionID_28979e8d,
  @OnCompleteActionID_Clear = 1,
  @OnOverdueActionID = @OnOverdueActionID_28979e8d,
  @OnOverdueActionID_Clear = 1,
  @OnPercentChangeActionID = @OnPercentChangeActionID_28979e8d,
  @OnPercentChangeActionID_Clear = 1,
  @IsActive = @IsActive_28979e8d;

GO

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
DECLARE @ID_557c3859 UNIQUEIDENTIFIER,
@Name_557c3859 NVARCHAR(100),
@Description_557c3859 NVARCHAR(MAX),
@IconClass_557c3859 NVARCHAR(100),
@DefaultPriority_557c3859 NVARCHAR(20),
@OnAssignActionID_557c3859 UNIQUEIDENTIFIER,
@OnCompleteActionID_557c3859 UNIQUEIDENTIFIER,
@OnOverdueActionID_557c3859 UNIQUEIDENTIFIER,
@OnPercentChangeActionID_557c3859 UNIQUEIDENTIFIER,
@IsActive_557c3859 BIT
SET
  @ID_557c3859 = '3F002EBA-0F6A-4433-BD98-83BC5982E916'
SET
  @Name_557c3859 = N'Deliverable'
SET
  @Description_557c3859 = N'A concrete output or artifact to be produced'
SET
  @IconClass_557c3859 = N'fa-solid fa-file-export'
SET
  @DefaultPriority_557c3859 = N'High'
SET
  @IsActive_557c3859 = 1
EXEC [__mj_BizAppsTasks].spCreateTaskType @ID = @ID_557c3859,
  @Name = @Name_557c3859,
  @Description = @Description_557c3859,
  @IconClass = @IconClass_557c3859,
  @DefaultPriority = @DefaultPriority_557c3859,
  @OnAssignActionID = @OnAssignActionID_557c3859,
  @OnAssignActionID_Clear = 1,
  @OnCompleteActionID = @OnCompleteActionID_557c3859,
  @OnCompleteActionID_Clear = 1,
  @OnOverdueActionID = @OnOverdueActionID_557c3859,
  @OnOverdueActionID_Clear = 1,
  @OnPercentChangeActionID = @OnPercentChangeActionID_557c3859,
  @OnPercentChangeActionID_Clear = 1,
  @IsActive = @IsActive_557c3859;

GO

-- Save MJ_BizApps_Tasks: Task Roles (core SP call only)
DECLARE @ID_50df5d1f UNIQUEIDENTIFIER,
@Name_50df5d1f NVARCHAR(100),
@Description_50df5d1f NVARCHAR(MAX),
@Sequence_50df5d1f INT
SET
  @ID_50df5d1f = 'E1DFE8EA-3A94-45BC-9E7E-7421CC4E8235'
SET
  @Name_50df5d1f = N'Primary'
SET
  @Description_50df5d1f = N'Primary person responsible for completing the task'
SET
  @Sequence_50df5d1f = 10
EXEC [__mj_BizAppsTasks].spCreateTaskRole @ID = @ID_50df5d1f,
  @Name = @Name_50df5d1f,
  @Description = @Description_50df5d1f,
  @Sequence = @Sequence_50df5d1f;

GO

-- Save MJ_BizApps_Tasks: Task Roles (core SP call only)
DECLARE @ID_a6a42771 UNIQUEIDENTIFIER,
@Name_a6a42771 NVARCHAR(100),
@Description_a6a42771 NVARCHAR(MAX),
@Sequence_a6a42771 INT
SET
  @ID_a6a42771 = 'D682BD3B-213D-4239-9FBA-4E28F60EC763'
SET
  @Name_a6a42771 = N'Reviewer'
SET
  @Description_a6a42771 = N'Reviews and approves the completed work'
SET
  @Sequence_a6a42771 = 20
EXEC [__mj_BizAppsTasks].spCreateTaskRole @ID = @ID_a6a42771,
  @Name = @Name_a6a42771,
  @Description = @Description_a6a42771,
  @Sequence = @Sequence_a6a42771;

GO

-- Save MJ_BizApps_Tasks: Task Roles (core SP call only)
DECLARE @ID_f3005d55 UNIQUEIDENTIFIER,
@Name_f3005d55 NVARCHAR(100),
@Description_f3005d55 NVARCHAR(MAX),
@Sequence_f3005d55 INT
SET
  @ID_f3005d55 = '561A6B4A-8FC4-42EA-9B47-C80E4E9F65D4'
SET
  @Name_f3005d55 = N'Observer'
SET
  @Description_f3005d55 = N'Kept informed of progress but not actively working on the task'
SET
  @Sequence_f3005d55 = 30
EXEC [__mj_BizAppsTasks].spCreateTaskRole @ID = @ID_f3005d55,
  @Name = @Name_f3005d55,
  @Description = @Description_f3005d55,
  @Sequence = @Sequence_f3005d55;

GO

-- Save MJ_BizApps_Tasks: Task Notification Configs (core SP call only)
DECLARE @ID_76cf7535 UNIQUEIDENTIFIER,
@TaskTypeID_76cf7535 UNIQUEIDENTIFIER,
@OverdueNotificationsEnabled_76cf7535 BIT,
@OverdueGracePeriodHours_76cf7535 INT,
@OverdueRepeatIntervalHours_76cf7535 INT,
@NotifyAssignees_76cf7535 BIT,
@NotifyCreator_76cf7535 BIT,
@OverdueActionID_76cf7535 UNIQUEIDENTIFIER
SET
  @ID_76cf7535 = '47883863-B19C-483E-A380-4F4C45611B60'
SET
  @OverdueNotificationsEnabled_76cf7535 = 1
SET
  @OverdueGracePeriodHours_76cf7535 = 0
SET
  @OverdueRepeatIntervalHours_76cf7535 = 24
SET
  @NotifyAssignees_76cf7535 = 1
SET
  @NotifyCreator_76cf7535 = 1
EXEC [__mj_BizAppsTasks].spCreateTaskNotificationConfig @ID = @ID_76cf7535,
  @TaskTypeID = @TaskTypeID_76cf7535,
  @TaskTypeID_Clear = 1,
  @OverdueNotificationsEnabled = @OverdueNotificationsEnabled_76cf7535,
  @OverdueGracePeriodHours = @OverdueGracePeriodHours_76cf7535,
  @OverdueRepeatIntervalHours = @OverdueRepeatIntervalHours_76cf7535,
  @NotifyAssignees = @NotifyAssignees_76cf7535,
  @NotifyCreator = @NotifyCreator_76cf7535,
  @OverdueActionID = @OverdueActionID_76cf7535,
  @OverdueActionID_Clear = 1;

GO


-- End of SQL Logging Session
-- Session ID: d22fb82f-8795-4d89-b6b4-09cee42fcb33
-- Completed: 2026-06-10T21:14:43.897Z
-- Duration: 462ms
-- Total Statements: 8
