-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj_bizappstasks;
SET search_path TO __mj_bizappstasks, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- NOTE: Earlier converter versions made INTEGER to BOOLEAN cast implicit by
-- modifying the system catalog so SS-style INSERT INTO bool_col VALUES (1)
-- would work. That modification required pg_catalog write privileges, which
-- managed PG (RDS, Aurora, Cloud SQL, Azure) does not grant. As of v5.30 all
-- bulk INSERTs are emitted with native TRUE/FALSE values directly, so the
-- cast modification is no longer needed. Removed to support managed-PG
-- installs out of the box.


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- SQL Logging Session
-- Session ID: 6117d6d5-6cae-4042-91c3-4be160eec6ee
-- Started: 2026-06-23T21:14:52.199Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Tasks: Task Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('5961EDE5-B996-4083-BE48-64634B4D8D1C', 'Approval Request', 'An approval/decision workflow request routed to one or more approvers. Consumers wire OnReject/OnCancel/OnComplete actions to feed the decision back to the source record.', 'fa-solid fa-stamp', 'High', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskDecisionOutcome" ("ID", "Name", "Code", "Description", "Sequence", "IsTerminal", "IsActive")
VALUES ('17597703-5724-4FC8-8A13-28CF5BA96E05', 'Approved', 'Approved', 'The request was approved without conditions.', 10, TRUE, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskDecisionOutcome" ("ID", "Name", "Code", "Description", "Sequence", "IsTerminal", "IsActive")
VALUES ('94C600A5-2CAB-4B52-A9D2-995768EAABD5', 'Rejected', 'Rejected', 'The request was rejected.', 20, TRUE, TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskDecisionOutcome" ("ID", "Name", "Code", "Description", "Sequence", "IsTerminal", "IsActive")
VALUES ('06C79086-AC2D-4E54-ADDB-CCAFC46D0DB7', 'Approved With Conditions', 'ApprovedWithConditions', 'The request was approved subject to the conditions in the decision notes.', 30, TRUE, TRUE)
ON CONFLICT ("ID") DO NOTHING;


-- ===================== Other =====================

-- End of SQL Logging Session
-- Session ID: 6117d6d5-6cae-4042-91c3-4be160eec6ee
-- Completed: 2026-06-23T21:14:52.582Z
-- Duration: 383ms
-- Total Statements: 4
