-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj_bizappstasks;
SET search_path TO __mj_bizappstasks, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- NOTE: Earlier converter versions made INTEGER to BOOLEAN cast implicit by
-- modifying the system catalog so SS-style INSERT INTO bool_col VALUES (1)
-- would work. That modification required pg_catalog write privileges, which
-- managed PG (RDS, Aurora, Cloud SQL, Azure) does not grant. As of v5.30 all
-- bulk INSERTs are emitted with native TRUE/FALSE values directly, so the
-- cast modification is no longer needed. Removed to support managed-PG
-- installs out of the box.


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- SQL Logging Session
-- Session ID: d22fb82f-8795-4d89-b6b4-09cee42fcb33
-- Started: 2026-06-10T21:14:43.435Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Tasks: Task Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('F7C1E8DE-8DAC-4BF8-943E-3D5A1210BE82', 'General', 'General-purpose task', 'fa-solid fa-circle-check', 'Medium', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('EA525DE3-B4A9-471C-AD13-1881E2055121', 'Action Item', 'Action item from a meeting or discussion', 'fa-solid fa-bolt', 'Medium', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('EE1A6B5A-A5AD-4A62-89DB-D16FFD2A415C', 'Follow-up', 'Follow-up on a previous discussion or decision', 'fa-solid fa-arrow-rotate-right', 'Medium', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('3F002EBA-0F6A-4433-BD98-83BC5982E916', 'Deliverable', 'A concrete output or artifact to be produced', 'fa-solid fa-file-export', 'High', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Roles (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskRole" ("ID", "Name", "Description", "Sequence")
VALUES ('E1DFE8EA-3A94-45BC-9E7E-7421CC4E8235', 'Primary', 'Primary person responsible for completing the task', 10)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Roles (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskRole" ("ID", "Name", "Description", "Sequence")
VALUES ('D682BD3B-213D-4239-9FBA-4E28F60EC763', 'Reviewer', 'Reviews and approves the completed work', 20)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Roles (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskRole" ("ID", "Name", "Description", "Sequence")
VALUES ('561A6B4A-8FC4-42EA-9B47-C80E4E9F65D4', 'Observer', 'Kept informed of progress but not actively working on the task', 30)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Tasks: Task Notification Configs (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappstasks."TaskNotificationConfig" ("ID", "OverdueNotificationsEnabled", "OverdueGracePeriodHours", "OverdueRepeatIntervalHours", "NotifyAssignees", "NotifyCreator")
VALUES ('47883863-B19C-483E-A380-4F4C45611B60', TRUE, 0, 24, TRUE, TRUE)
ON CONFLICT ("ID") DO NOTHING;


-- ===================== Other =====================

-- End of SQL Logging Session
-- Session ID: d22fb82f-8795-4d89-b6b4-09cee42fcb33
-- Completed: 2026-06-10T21:14:43.897Z
-- Duration: 462ms
-- Total Statements: 8
