-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj_bizappstasks;
SET search_path TO __mj_bizappstasks, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- NOTE: Earlier converter versions made INTEGER to BOOLEAN cast implicit by
-- modifying the system catalog so SS-style INSERT INTO bool_col VALUES (1)
-- would work. That modification required pg_catalog write privileges, which
-- managed PG (RDS, Aurora, Cloud SQL, Azure) does not grant. As of v5.30 all
-- bulk INSERTs are emitted with native TRUE/FALSE values directly, so the
-- cast modification is no longer needed. Removed to support managed-PG
-- installs out of the box.


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- SQL Logging Session
-- Session ID: 6117d6d5-6cae-4042-91c3-4be160eec6ee
-- Started: 2026-06-23T21:14:52.199Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_45bb317a UUID;
--   p_Name_45bb317a VARCHAR(100);
--   p_Description_45bb317a TEXT;
--   p_IconClass_45bb317a VARCHAR(100);
--   p_DefaultPriority_45bb317a VARCHAR(20);
--   p_OnAssignActionID_45bb317a UUID;
--   p_OnCompleteActionID_45bb317a UUID;
--   p_OnOverdueActionID_45bb317a UUID;
--   p_OnPercentChangeActionID_45bb317a UUID;
--   p_IsActive_45bb317a BOOLEAN;
--   p_OnRejectActionID_45bb317a UUID;
--   p_OnCancelActionID_45bb317a UUID;
-- BEGIN
--   p_ID_45bb317a := '5961EDE5-B996-4083-BE48-64634B4D8D1C';
--   p_Name_45bb317a := 'Approval Request';
--   p_Description_45bb317a := 'An approval/decision workflow request routed to one or more approvers. Consumers wire OnReject/OnCancel/OnComplete actions to feed the decision back to the source record.';
--   p_IconClass_45bb317a := 'fa-solid fa-stamp';
--   p_DefaultPriority_45bb317a := 'High';
--   p_IsActive_45bb317a := TRUE;
--   PERFORM __mj_bizappstasks."spCreateTaskType"(p_ID := p_ID_45bb317a, p_Name := p_Name_45bb317a, p_Description := p_Description_45bb317a, p_IconClass := p_IconClass_45bb317a, p_DefaultPriority := p_DefaultPriority_45bb317a, p_OnAssignActionID := p_OnAssignActionID_45bb317a, p_OnAssignActionID_Clear := TRUE, p_OnCompleteActionID := p_OnCompleteActionID_45bb317a, p_OnCompleteActionID_Clear := TRUE, p_OnOverdueActionID := p_OnOverdueActionID_45bb317a, p_OnOverdueActionID_Clear := TRUE, p_OnPercentChangeActionID := p_OnPercentChangeActionID_45bb317a, p_OnPercentChangeActionID_Clear := TRUE, p_IsActive := p_IsActive_45bb317a, p_OnRejectActionID := p_OnRejectActionID_45bb317a, p_OnRejectActionID_Clear := TRUE, p_OnCancelActionID := p_OnCancelActionID_45bb317a, p_OnCancelActionID_Clear := TRUE);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_f7145d84 UUID;
--   p_Name_f7145d84 VARCHAR(100);
--   p_Code_f7145d84 VARCHAR(50);
--   p_Description_f7145d84 TEXT;
--   p_Sequence_f7145d84 INTEGER;
--   p_IsTerminal_f7145d84 BOOLEAN;
--   p_IsActive_f7145d84 BOOLEAN;
-- BEGIN
--   p_ID_f7145d84 := '17597703-5724-4FC8-8A13-28CF5BA96E05';
--   p_Name_f7145d84 := 'Approved';
--   p_Code_f7145d84 := 'Approved';
--   p_Description_f7145d84 := 'The request was approved without conditions.';
--   p_Sequence_f7145d84 := 10;
--   p_IsTerminal_f7145d84 := TRUE;
--   p_IsActive_f7145d84 := TRUE;
--   PERFORM __mj_bizappstasks."spCreateTaskDecisionOutcome"(p_ID := p_ID_f7145d84, p_Name := p_Name_f7145d84, p_Code := p_Code_f7145d84, p_Description := p_Description_f7145d84, p_Sequence := p_Sequence_f7145d84, p_IsTerminal := p_IsTerminal_f7145d84, p_IsActive := p_IsActive_f7145d84);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_ffb26e89 UUID;
--   p_Name_ffb26e89 VARCHAR(100);
--   p_Code_ffb26e89 VARCHAR(50);
--   p_Description_ffb26e89 TEXT;
--   p_Sequence_ffb26e89 INTEGER;
--   p_IsTerminal_ffb26e89 BOOLEAN;
--   p_IsActive_ffb26e89 BOOLEAN;
-- BEGIN
--   p_ID_ffb26e89 := '94C600A5-2CAB-4B52-A9D2-995768EAABD5';
--   p_Name_ffb26e89 := 'Rejected';
--   p_Code_ffb26e89 := 'Rejected';
--   p_Description_ffb26e89 := 'The request was rejected.';
--   p_Sequence_ffb26e89 := 20;
--   p_IsTerminal_ffb26e89 := TRUE;
--   p_IsActive_ffb26e89 := TRUE;
--   PERFORM __mj_bizappstasks."spCreateTaskDecisionOutcome"(p_ID := p_ID_ffb26e89, p_Name := p_Name_ffb26e89, p_Code := p_Code_ffb26e89, p_Description := p_Description_ffb26e89, p_Sequence := p_Sequence_ffb26e89, p_IsTerminal := p_IsTerminal_ffb26e89, p_IsActive := p_IsActive_ffb26e89);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Decision Outcomes (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_13e57da9 UUID;
--   p_Name_13e57da9 VARCHAR(100);
--   p_Code_13e57da9 VARCHAR(50);
--   p_Description_13e57da9 TEXT;
--   p_Sequence_13e57da9 INTEGER;
--   p_IsTerminal_13e57da9 BOOLEAN;
--   p_IsActive_13e57da9 BOOLEAN;
-- BEGIN
--   p_ID_13e57da9 := '06C79086-AC2D-4E54-ADDB-CCAFC46D0DB7';
--   p_Name_13e57da9 := 'Approved With Conditions';
--   p_Code_13e57da9 := 'ApprovedWithConditions';
--   p_Description_13e57da9 := 'The request was approved subject to the conditions in the decision notes.';
--   p_Sequence_13e57da9 := 30;
--   p_IsTerminal_13e57da9 := TRUE;
--   p_IsActive_13e57da9 := TRUE;
--   PERFORM __mj_bizappstasks."spCreateTaskDecisionOutcome"(p_ID := p_ID_13e57da9, p_Name := p_Name_13e57da9, p_Code := p_Code_13e57da9, p_Description := p_Description_13e57da9, p_Sequence := p_Sequence_13e57da9, p_IsTerminal := p_IsTerminal_13e57da9, p_IsActive := p_IsActive_13e57da9);
-- END $mj$;


-- ===================== Other =====================

-- End of SQL Logging Session
-- Session ID: 6117d6d5-6cae-4042-91c3-4be160eec6ee
-- Completed: 2026-06-23T21:14:52.582Z
-- Duration: 383ms
-- Total Statements: 4
