-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj_BizAppsTasks;
SET search_path TO __mj_BizAppsTasks, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- NOTE: Earlier converter versions made INTEGER to BOOLEAN cast implicit by
-- modifying the system catalog so SS-style INSERT INTO bool_col VALUES (1)
-- would work. That modification required pg_catalog write privileges, which
-- managed PG (RDS, Aurora, Cloud SQL, Azure) does not grant. As of v5.30 all
-- bulk INSERTs are emitted with native TRUE/FALSE values directly, so the
-- cast modification is no longer needed. Removed to support managed-PG
-- installs out of the box.


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- SQL Logging Session
-- Session ID: d22fb82f-8795-4d89-b6b4-09cee42fcb33
-- Started: 2026-06-10T21:14:43.435Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_7c1991f8 UUID;
--   p_Name_7c1991f8 VARCHAR(100);
--   p_Description_7c1991f8 TEXT;
--   p_IconClass_7c1991f8 VARCHAR(100);
--   p_DefaultPriority_7c1991f8 VARCHAR(20);
--   p_OnAssignActionID_7c1991f8 UUID;
--   p_OnCompleteActionID_7c1991f8 UUID;
--   p_OnOverdueActionID_7c1991f8 UUID;
--   p_OnPercentChangeActionID_7c1991f8 UUID;
--   p_IsActive_7c1991f8 BOOLEAN;
-- BEGIN
--   p_ID_7c1991f8 := 'F7C1E8DE-8DAC-4BF8-943E-3D5A1210BE82';
--   p_Name_7c1991f8 := 'General';
--   p_Description_7c1991f8 := 'General-purpose task';
--   p_IconClass_7c1991f8 := 'fa-solid fa-circle-check';
--   p_DefaultPriority_7c1991f8 := 'Medium';
--   p_IsActive_7c1991f8 := TRUE;
--   PERFORM __mj_BizAppsTasks."spCreateTaskType"(p_ID := p_ID_7c1991f8, p_Name := p_Name_7c1991f8, p_Description := p_Description_7c1991f8, p_IconClass := p_IconClass_7c1991f8, p_DefaultPriority := p_DefaultPriority_7c1991f8, p_OnAssignActionID := p_OnAssignActionID_7c1991f8, p_OnAssignActionID_Clear := TRUE, p_OnCompleteActionID := p_OnCompleteActionID_7c1991f8, p_OnCompleteActionID_Clear := TRUE, p_OnOverdueActionID := p_OnOverdueActionID_7c1991f8, p_OnOverdueActionID_Clear := TRUE, p_OnPercentChangeActionID := p_OnPercentChangeActionID_7c1991f8, p_OnPercentChangeActionID_Clear := TRUE, p_IsActive := p_IsActive_7c1991f8);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_9beba79b UUID;
--   p_Name_9beba79b VARCHAR(100);
--   p_Description_9beba79b TEXT;
--   p_IconClass_9beba79b VARCHAR(100);
--   p_DefaultPriority_9beba79b VARCHAR(20);
--   p_OnAssignActionID_9beba79b UUID;
--   p_OnCompleteActionID_9beba79b UUID;
--   p_OnOverdueActionID_9beba79b UUID;
--   p_OnPercentChangeActionID_9beba79b UUID;
--   p_IsActive_9beba79b BOOLEAN;
-- BEGIN
--   p_ID_9beba79b := 'EA525DE3-B4A9-471C-AD13-1881E2055121';
--   p_Name_9beba79b := 'Action Item';
--   p_Description_9beba79b := 'Action item from a meeting or discussion';
--   p_IconClass_9beba79b := 'fa-solid fa-bolt';
--   p_DefaultPriority_9beba79b := 'Medium';
--   p_IsActive_9beba79b := TRUE;
--   PERFORM __mj_BizAppsTasks."spCreateTaskType"(p_ID := p_ID_9beba79b, p_Name := p_Name_9beba79b, p_Description := p_Description_9beba79b, p_IconClass := p_IconClass_9beba79b, p_DefaultPriority := p_DefaultPriority_9beba79b, p_OnAssignActionID := p_OnAssignActionID_9beba79b, p_OnAssignActionID_Clear := TRUE, p_OnCompleteActionID := p_OnCompleteActionID_9beba79b, p_OnCompleteActionID_Clear := TRUE, p_OnOverdueActionID := p_OnOverdueActionID_9beba79b, p_OnOverdueActionID_Clear := TRUE, p_OnPercentChangeActionID := p_OnPercentChangeActionID_9beba79b, p_OnPercentChangeActionID_Clear := TRUE, p_IsActive := p_IsActive_9beba79b);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_28979e8d UUID;
--   p_Name_28979e8d VARCHAR(100);
--   p_Description_28979e8d TEXT;
--   p_IconClass_28979e8d VARCHAR(100);
--   p_DefaultPriority_28979e8d VARCHAR(20);
--   p_OnAssignActionID_28979e8d UUID;
--   p_OnCompleteActionID_28979e8d UUID;
--   p_OnOverdueActionID_28979e8d UUID;
--   p_OnPercentChangeActionID_28979e8d UUID;
--   p_IsActive_28979e8d BOOLEAN;
-- BEGIN
--   p_ID_28979e8d := 'EE1A6B5A-A5AD-4A62-89DB-D16FFD2A415C';
--   p_Name_28979e8d := 'Follow-up';
--   p_Description_28979e8d := 'Follow-up on a previous discussion or decision';
--   p_IconClass_28979e8d := 'fa-solid fa-arrow-rotate-right';
--   p_DefaultPriority_28979e8d := 'Medium';
--   p_IsActive_28979e8d := TRUE;
--   PERFORM __mj_BizAppsTasks."spCreateTaskType"(p_ID := p_ID_28979e8d, p_Name := p_Name_28979e8d, p_Description := p_Description_28979e8d, p_IconClass := p_IconClass_28979e8d, p_DefaultPriority := p_DefaultPriority_28979e8d, p_OnAssignActionID := p_OnAssignActionID_28979e8d, p_OnAssignActionID_Clear := TRUE, p_OnCompleteActionID := p_OnCompleteActionID_28979e8d, p_OnCompleteActionID_Clear := TRUE, p_OnOverdueActionID := p_OnOverdueActionID_28979e8d, p_OnOverdueActionID_Clear := TRUE, p_OnPercentChangeActionID := p_OnPercentChangeActionID_28979e8d, p_OnPercentChangeActionID_Clear := TRUE, p_IsActive := p_IsActive_28979e8d);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Types (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_557c3859 UUID;
--   p_Name_557c3859 VARCHAR(100);
--   p_Description_557c3859 TEXT;
--   p_IconClass_557c3859 VARCHAR(100);
--   p_DefaultPriority_557c3859 VARCHAR(20);
--   p_OnAssignActionID_557c3859 UUID;
--   p_OnCompleteActionID_557c3859 UUID;
--   p_OnOverdueActionID_557c3859 UUID;
--   p_OnPercentChangeActionID_557c3859 UUID;
--   p_IsActive_557c3859 BOOLEAN;
-- BEGIN
--   p_ID_557c3859 := '3F002EBA-0F6A-4433-BD98-83BC5982E916';
--   p_Name_557c3859 := 'Deliverable';
--   p_Description_557c3859 := 'A concrete output or artifact to be produced';
--   p_IconClass_557c3859 := 'fa-solid fa-file-export';
--   p_DefaultPriority_557c3859 := 'High';
--   p_IsActive_557c3859 := TRUE;
--   PERFORM __mj_BizAppsTasks."spCreateTaskType"(p_ID := p_ID_557c3859, p_Name := p_Name_557c3859, p_Description := p_Description_557c3859, p_IconClass := p_IconClass_557c3859, p_DefaultPriority := p_DefaultPriority_557c3859, p_OnAssignActionID := p_OnAssignActionID_557c3859, p_OnAssignActionID_Clear := TRUE, p_OnCompleteActionID := p_OnCompleteActionID_557c3859, p_OnCompleteActionID_Clear := TRUE, p_OnOverdueActionID := p_OnOverdueActionID_557c3859, p_OnOverdueActionID_Clear := TRUE, p_OnPercentChangeActionID := p_OnPercentChangeActionID_557c3859, p_OnPercentChangeActionID_Clear := TRUE, p_IsActive := p_IsActive_557c3859);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Roles (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_50df5d1f UUID;
--   p_Name_50df5d1f VARCHAR(100);
--   p_Description_50df5d1f TEXT;
--   p_Sequence_50df5d1f INTEGER;
-- BEGIN
--   p_ID_50df5d1f := 'E1DFE8EA-3A94-45BC-9E7E-7421CC4E8235';
--   p_Name_50df5d1f := 'Primary';
--   p_Description_50df5d1f := 'Primary person responsible for completing the task';
--   p_Sequence_50df5d1f := 10;
--   PERFORM __mj_BizAppsTasks."spCreateTaskRole"(p_ID := p_ID_50df5d1f, p_Name := p_Name_50df5d1f, p_Description := p_Description_50df5d1f, p_Sequence := p_Sequence_50df5d1f);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Roles (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_a6a42771 UUID;
--   p_Name_a6a42771 VARCHAR(100);
--   p_Description_a6a42771 TEXT;
--   p_Sequence_a6a42771 INTEGER;
-- BEGIN
--   p_ID_a6a42771 := 'D682BD3B-213D-4239-9FBA-4E28F60EC763';
--   p_Name_a6a42771 := 'Reviewer';
--   p_Description_a6a42771 := 'Reviews and approves the completed work';
--   p_Sequence_a6a42771 := 20;
--   PERFORM __mj_BizAppsTasks."spCreateTaskRole"(p_ID := p_ID_a6a42771, p_Name := p_Name_a6a42771, p_Description := p_Description_a6a42771, p_Sequence := p_Sequence_a6a42771);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Roles (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_f3005d55 UUID;
--   p_Name_f3005d55 VARCHAR(100);
--   p_Description_f3005d55 TEXT;
--   p_Sequence_f3005d55 INTEGER;
-- BEGIN
--   p_ID_f3005d55 := '561A6B4A-8FC4-42EA-9B47-C80E4E9F65D4';
--   p_Name_f3005d55 := 'Observer';
--   p_Description_f3005d55 := 'Kept informed of progress but not actively working on the task';
--   p_Sequence_f3005d55 := 30;
--   PERFORM __mj_BizAppsTasks."spCreateTaskRole"(p_ID := p_ID_f3005d55, p_Name := p_Name_f3005d55, p_Description := p_Description_f3005d55, p_Sequence := p_Sequence_f3005d55);
-- END $mj$;

-- Save MJ_BizApps_Tasks: Task Notification Configs (core SP call only)
-- DO $mj$
-- DECLARE
--   p_ID_76cf7535 UUID;
--   p_TaskTypeID_76cf7535 UUID;
--   p_OverdueNotificationsEnabled_76cf7535 BOOLEAN;
--   p_OverdueGracePeriodHours_76cf7535 INTEGER;
--   p_OverdueRepeatIntervalHours_76cf7535 INTEGER;
--   p_NotifyAssignees_76cf7535 BOOLEAN;
--   p_NotifyCreator_76cf7535 BOOLEAN;
--   p_OverdueActionID_76cf7535 UUID;
-- BEGIN
--   p_ID_76cf7535 := '47883863-B19C-483E-A380-4F4C45611B60';
--   p_OverdueNotificationsEnabled_76cf7535 := TRUE;
--   p_OverdueGracePeriodHours_76cf7535 := 0;
--   p_OverdueRepeatIntervalHours_76cf7535 := 24;
--   p_NotifyAssignees_76cf7535 := TRUE;
--   p_NotifyCreator_76cf7535 := TRUE;
--   PERFORM __mj_BizAppsTasks."spCreateTaskNotificationConfig"(p_ID := p_ID_76cf7535, p_TaskTypeID := p_TaskTypeID_76cf7535, p_TaskTypeID_Clear := TRUE, p_OverdueNotificationsEnabled := p_OverdueNotificationsEnabled_76cf7535, p_OverdueGracePeriodHours := p_OverdueGracePeriodHours_76cf7535, p_OverdueRepeatIntervalHours := p_OverdueRepeatIntervalHours_76cf7535, p_NotifyAssignees := p_NotifyAssignees_76cf7535, p_NotifyCreator := p_NotifyCreator_76cf7535, p_OverdueActionID := p_OverdueActionID_76cf7535, p_OverdueActionID_Clear := TRUE);
-- END $mj$;


-- ===================== Other =====================

-- End of SQL Logging Session
-- Session ID: d22fb82f-8795-4d89-b6b4-09cee42fcb33
-- Completed: 2026-06-10T21:14:43.897Z
-- Duration: 462ms
-- Total Statements: 8
